name: futsal_dai
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.11.3

dependencies:
  cached_network_image: ^3.4.1
  flutter:
    sdk: flutter
  flutter_image_compress: ^2.5.0
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.3.0
  geocoding: ^5.0.0
  geolocator: ^14.0.3
  get: ^4.7.3
  image_picker: ^1.2.3
  intl: ^0.20.3
  package_info_plus: ^10.2.0
  path: ^1.9.1
  path_provider: ^2.1.6
  share_plus: ^13.2.1
  shimmer: ^3.0.0
  supabase_flutter: ^2.15.3
  url_launcher: ^6.3.2
  webview_flutter: ^4.14.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
